# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideEffect',
        ),
    ]
