# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_auto_20180123_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='caused_by',
        ),
    ]
