# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0006_remove_sideeffect_caused_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='causedby',
            field=models.ManyToManyField(blank=True, null=True, to='visual.Chemical'),
        ),
    ]
