# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0008_auto_20180123_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('HGNC', models.IntegerField()),
                ('UniProt', models.CharField(max_length=6)),
                ('Chromosome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='sideeffect',
            name='caused_by',
        ),
        migrations.AddField(
            model_name='chemical',
            name='side_effects',
            field=models.ManyToManyField(blank=True, to='visual.SideEffect'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='total_affected_genes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='total_side_effects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='affected_genes',
            field=models.ManyToManyField(blank=True, to='visual.Gene'),
        ),
    ]
