# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0009_auto_20180124_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='affected_genes',
            new_name='associated_genes',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='side_effects',
            new_name='associated_side_effects',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='total_affected_genes',
            new_name='total_associated_genes',
        ),
        migrations.RenameField(
            model_name='chemical',
            old_name='total_side_effects',
            new_name='total_associated_side_effects',
        ),
        migrations.AddField(
            model_name='gene',
            name='Symbol',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='associated_side_effects',
            field=models.ManyToManyField(blank=True, to='visual.SideEffect'),
        ),
        migrations.AddField(
            model_name='gene',
            name='total_associated_chemicals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='total_associated_side_effects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='total_associated_chemicals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='total_associated_genes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='Chromosome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gene',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
