# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0010_auto_20180124_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='name',
        ),
        migrations.AlterField(
            model_name='gene',
            name='UniProt',
            field=models.CharField(max_length=300),
        ),
    ]
