# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0011_auto_20180124_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='chem_similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('chem_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chem_a_set', to='visual.Chemical')),
                ('chem_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chem_b_set', to='visual.Chemical')),
            ],
        ),
        migrations.CreateModel(
            name='gene_similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similairty', models.FloatField(blank=True, null=True)),
                ('interaction', models.FloatField(blank=True, null=True)),
                ('gene_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_a_set', to='visual.Gene')),
                ('gene_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_b_set', to='visual.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='se_similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('se_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_a_set', to='visual.SideEffect')),
                ('se_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_b_set', to='visual.SideEffect')),
            ],
        ),
    ]
