# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0012_chem_similarity_gene_similarity_se_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='intermodel',
            field=models.ManyToManyField(through='visual.chem_similarity', to='visual.Chemical'),
        ),
        migrations.AddField(
            model_name='gene',
            name='intermodel',
            field=models.ManyToManyField(through='visual.gene_similarity', to='visual.Gene'),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='intermodel',
            field=models.ManyToManyField(through='visual.se_similarity', to='visual.SideEffect'),
        ),
    ]
