# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0013_auto_20180204_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene_similarity',
            old_name='similairty',
            new_name='similarity',
        ),
    ]
